from flask.ext import assets

app_js = assets.Bundle('js/jquery.js',
                       'js/jquery.foundation.mediaQueryToggle.js',
                       'js/jquery.foundation.forms.js',
                       'js/jquery.event.move.js',
                       'js/jquery.event.swipe.js',
                       'js/jquery.foundation.reveal.js',
                       'js/jquery.foundation.navigation.js',
                       'js/jquery.foundation.buttons.js',
                       'js/jquery.foundation.tabs.js',
                       'js/jquery.foundation.tooltips.js',
                       'js/jquery.foundation.accordion.js',
                       'js/jquery.placeholder.js',
                       'js/jquery.foundation.alerts.js',
                       'js/jquery.foundation.topbar.js',
                       'chosen/chosen.jquery.js',
                       'js/sugar.js',
                       'js/d3.v2.js',
                       'js/nv.d3.js',
                       'js/app.js',
                       filters='yui_js',
                       output='gen/app.js')

app_css = assets.Bundle('css/foundation.css',
                        'chosen/chosen.css',
                        'css/nv.d3.css',
                        'css/app.css',
                        filters='yui_css',
                        output='gen/app.css')
